<#
.SYNOPSIS
  Generates ground-truth token streams for differential-testing Husk's lexer.

.DESCRIPTION
  Runs the real PowerShell tokenizer over every corpus fixture and records the
  token stream it produces. Husk's lexer is then tested against truth rather
  than against our own reading of the grammar.

  The lexer is the highest-variance component of the project; this is what
  converts it from a judgement call into a mechanical convergence problem.
  See docs/husk-spec.md section 6.

.EXAMPLE
  pwsh -File scripts/husk/generate-lexer-oracle.ps1
#>
[CmdletBinding()]
param(
  [string]$CorpusFile = 'src/features/husk/corpus/fixtures/invoke-obfuscation.json',
  [string]$OutFile = 'src/features/husk/corpus/fixtures/lexer-oracle.json'
)

$ErrorActionPreference = 'Stop'

function Get-TokenStream {
  param([string]$Source)

  $tokens = $null; $parseErrors = $null
  [void][System.Management.Automation.Language.Parser]::ParseInput($Source, [ref]$tokens, [ref]$parseErrors)

  $flat = foreach ($t in $tokens) {
    [ordered]@{
      kind  = $t.Kind.ToString()
      text  = $t.Text
      start = $t.Extent.StartOffset
      end   = $t.Extent.EndOffset
    }
  }

  [ordered]@{
    tokens     = @($flat)
    errorCount = @($parseErrors).Count
  }
}

$corpus = Get-Content $CorpusFile -Raw | ConvertFrom-Json
$cases = [System.Collections.Generic.List[object]]::new()

# The corpus fixtures, which are real obfuscator output.
foreach ($fixture in $corpus.fixtures) {
  $result = Get-TokenStream -Source $fixture.obfuscated
  $cases.Add([ordered]@{
    id         = "corpus/$($fixture.id)"
    source     = $fixture.obfuscated
    tokens     = $result.tokens
    errorCount = $result.errorCount
  })
}

# Plus targeted cases for the lexer edge cases that are easy to get wrong and
# that the corpus may not happen to cover.
$edgeCases = [ordered]@{
  'expandable-string-subexpr'  = '"result: $($a.b[0]) done"'
  'nested-subexpression'       = '$($x = $(1 + 2); $x)'
  'here-string-literal'        = "@'`nliteral `$notavar`n'@"
  'here-string-expandable'     = "@`"`nvalue is `$x`n`"@"
  'backtick-escapes'           = '"tab`there`nnewline"'
  'backtick-in-command'        = 'Wri`te-Ho`st "x"'
  'splatting'                  = '$args = @{A=1}; Get-Thing @args'
  'unicode-dash-parameter'     = "Get-Thing `u{2013}Name value"
  'smart-quote-string'         = "`u{201c}hello`u{201d}"
  'array-index-chain'          = '$a[0][1].Method().Property'
  'type-literal-generic'       = '[System.Collections.Generic.List[string]]::new()'
  'format-operator'            = "'{1}{0}' -f 'a','b'"
  'argument-mode-dash'         = 'Get-Thing -Name -5'
  'expression-mode-dash'       = '$a -5'
  'number-suffixes'            = '1kb + 2mb + 0x1F + 1e3 + 100L'
  'ternary'                    = '$a ? 1 : 2'
  'null-coalesce'              = '$a ?? $b'
  'comment-then-code'          = "# comment`nWrite-Host 'x'"
  'block-comment'              = '<# block #> Write-Host 1'
  'label-and-break'            = ':outer while ($true) { break outer }'
  'variable-braced'            = '${weird name} = 1'
  'scope-qualified-variable'   = '$global:x + $env:PATH'
  'stream-redirect'            = 'cmd 2>&1 > out.txt'
  'dot-source'                 = '. .\script.ps1'
  'amp-invoke'                 = "& 'Write-Host' 'x'"
}

foreach ($name in $edgeCases.Keys) {
  $source = $edgeCases[$name]
  $result = Get-TokenStream -Source $source
  $cases.Add([ordered]@{
    id         = "edge/$name"
    source     = $source
    tokens     = $result.tokens
    errorCount = $result.errorCount
  })
}

$result = [ordered]@{
  '$comment'      = 'GENERATED by scripts/husk/generate-lexer-oracle.ps1 - do not edit by hand.'
  powerShellVersion = $PSVersionTable.PSVersion.ToString()
  cases           = $cases
}

$dir = Split-Path -Parent $OutFile
if ($dir -and -not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
$result | ConvertTo-Json -Depth 10 | Set-Content -Path $OutFile -Encoding utf8

"wrote $OutFile"
"  cases:  $($cases.Count)"
"  tokens: $(($cases | ForEach-Object { $_.tokens.Count } | Measure-Object -Sum).Sum)"
$withErrors = @($cases | Where-Object { $_.errorCount -gt 0 })
"  cases the real parser rejects: $($withErrors.Count)"
$withErrors | Select-Object -First 5 | ForEach-Object { "    $($_.id)" }
