<#
.SYNOPSIS
  Generates a layered deobfuscation corpus by composing Invoke-Obfuscation
  transforms, the way real droppers are built.

.DESCRIPTION
  The single-transform corpus answers "can Husk undo transform X". Real samples
  stack transforms - token obfuscation, then string obfuscation, then an
  encoder - and the interactions are where a deobfuscator actually breaks.

  Composing them mechanically is what makes coverage a measurement rather than
  a spot check: every combination is generated and scored, so no family can be
  quietly missed.

  Payloads stay benign - no malware is committed to this repo.

.EXAMPLE
  npm run husk:corpus:layered -- -InvokeObfuscationPath /tmp/io
#>
[CmdletBinding()]
param(
  [Parameter(Mandatory)][string]$InvokeObfuscationPath,
  [string]$OutFile = 'src/features/husk/corpus/fixtures/layered.json',
  [int]$MaxFixtures = 2000
)

$ErrorActionPreference = 'Stop'
Import-Module (Join-Path $InvokeObfuscationPath 'Invoke-Obfuscation.psd1') -Force

$payloads = [ordered]@{
  'write-host'  = 'Write-Host "hello husk"'
  'string-var'  = '$a = "husk"; Write-Host $a'
  'nested-call' = '$x = [System.Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes("husk")); Write-Host $x'
  'pipeline'    = "'a','b','c' | ForEach-Object { `$_.ToUpper() }"
}

# Layer 1: token-level obfuscation, read from the cmdlet's own ValidateSet.
$tokenTypes = (Get-Command Out-ObfuscatedTokenCommand).Parameters['TokenTypeToObfuscate'].Attributes |
  Where-Object { $_ -is [System.Management.Automation.ValidateSetAttribute] } |
  Select-Object -First 1 -ExpandProperty ValidValues

# Layer 3: whole-command encoders.
$encoders = @(
  'Out-EncodedAsciiCommand'
  'Out-EncodedHexCommand'
  'Out-EncodedOctalCommand'
  'Out-EncodedBinaryCommand'
  'Out-EncodedBXORCommand'
  'Out-CompressedCommand'
)

$fixtures = [System.Collections.Generic.List[object]]::new()
$skipped = 0
$failed = 0

function Add-Layered {
  param($Id, $Layers, $Payload, $Expected, $Obfuscated)

  if ([string]::IsNullOrWhiteSpace($Obfuscated)) { $script:failed++; return }
  if ($Obfuscated.Trim() -ceq $Expected.Trim()) { $script:skipped++; return }

  $fixtures.Add([ordered]@{
    id         = $Id
    layers     = $Layers
    transform  = ($Layers -join ' + ')
    payload    = $Payload
    expected   = $Expected
    obfuscated = $Obfuscated
  })
}

foreach ($name in $payloads.Keys) {
  $expected = $payloads[$name]

  foreach ($tokenType in $tokenTypes) {
    # One representative level per token type keeps the matrix tractable while
    # still covering every type.
    $level = 1
    try {
      $afterToken = Out-ObfuscatedTokenCommand -ScriptBlock ([ScriptBlock]::Create($expected)) `
        -TokenTypeToObfuscate $tokenType -ObfuscationLevel $level
    } catch { $failed++; continue }
    if ([string]::IsNullOrWhiteSpace($afterToken)) { $failed++; continue }

    # Two layers: token then string.
    foreach ($stringLevel in 1..3) {
      try {
        $afterString = Out-ObfuscatedStringCommand -ScriptBlock ([ScriptBlock]::Create($afterToken)) `
          -ObfuscationLevel $stringLevel
      } catch { $failed++; continue }

      Add-Layered -Id "$name/token-$tokenType+string-$stringLevel" `
        -Layers @("token-$tokenType", "string-$stringLevel") `
        -Payload $name -Expected $expected -Obfuscated $afterString

      # Three layers: token, string, then an encoder.
      foreach ($encoder in $encoders) {
        if ($fixtures.Count -ge $MaxFixtures) { break }
        try {
          $encoded = & $encoder -ScriptBlock ([ScriptBlock]::Create($afterString))
        } catch { $failed++; continue }

        Add-Layered -Id "$name/token-$tokenType+string-$stringLevel+$encoder" `
          -Layers @("token-$tokenType", "string-$stringLevel", $encoder) `
          -Payload $name -Expected $expected -Obfuscated $encoded
      }
    }

    # Two layers: token then an encoder, without the string pass.
    foreach ($encoder in $encoders) {
      if ($fixtures.Count -ge $MaxFixtures) { break }
      try {
        $encoded = & $encoder -ScriptBlock ([ScriptBlock]::Create($afterToken))
      } catch { $failed++; continue }

      Add-Layered -Id "$name/token-$tokenType+$encoder" `
        -Layers @("token-$tokenType", $encoder) `
        -Payload $name -Expected $expected -Obfuscated $encoded
    }
  }
}

$result = [ordered]@{
  '$comment'   = 'GENERATED by scripts/husk/generate-layered-corpus.ps1 - do not edit by hand.'
  generator    = 'Invoke-Obfuscation (composed)'
  generatedFor = 'layered commodity IR corpus (docs/husk-spec.md section 6)'
  payloads     = $payloads
  fixtures     = $fixtures
}

$dir = Split-Path -Parent $OutFile
if ($dir -and -not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
$result | ConvertTo-Json -Depth 10 -Compress | Set-Content -Path $OutFile -Encoding utf8

"wrote $OutFile"
"  fixtures: $($fixtures.Count)"
"  skipped as no-ops: $skipped"
"  transforms that errored: $failed"
