// Girih — mines the drill position bank.
// SPDX-License-Identifier: PolyForm-Small-Business-1.0.0
// Required Notice: Copyright 2026 Mo4n6 (https://github.com/Mo4n6/tools)
//
//   npm run girih:mine -- [minutes] [quota] [seed]
//
// Generates random minimal puzzles on every core, solves each one the human
// way, and keeps boards where a technique is the simplest move available. The
// result is written to src/features/girih/data/positions.json. Easy techniques
// fill their quota in seconds; Jellyfish and the quads take the time.

import { writeFileSync } from 'node:fs';
import { availableParallelism } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { Worker, isMainThread, parentPort, workerData } from 'node:worker_threads';

import { TECHNIQUES } from '../../src/features/girih/engine/catalog.ts';
import { decodePosition } from '../../src/features/girih/engine/bank.ts';
import { mine, type MineResult, type MineStats } from '../../src/features/girih/engine/miner.ts';
import { createRng, shuffle } from '../../src/features/girih/engine/random.ts';
import { simplestStep } from '../../src/features/girih/engine/stepper.ts';
import type { TechniqueId } from '../../src/features/girih/engine/types.ts';

type Job = { seed: number; deadline: number; cap: number };

if (!isMainThread) {
  const job = workerData as Job;
  const result = mine(createRng(job.seed), { deadline: job.deadline, cap: job.cap, now: () => Date.now() });
  parentPort?.postMessage(result);
} else {
  const minutes = Number(process.argv[2] ?? 10);
  const quota = Number(process.argv[3] ?? 60);
  const seed = Number(process.argv[4] ?? 20261011);
  const threads = Math.max(1, availableParallelism());
  const deadline = Date.now() + minutes * 60_000;
  console.log(`mining for ${minutes} min on ${threads} threads, quota ${quota} per technique`);

  const here = dirname(fileURLToPath(import.meta.url));
  const results = await Promise.all(
    Array.from(
      { length: threads },
      (_, i) =>
        new Promise<MineResult>((resolve, reject) => {
          const worker = new Worker(fileURLToPath(import.meta.url), {
            workerData: { seed: seed + i * 7919, deadline, cap: quota * 2 } satisfies Job,
          });
          worker.once('message', resolve);
          worker.once('error', reject);
        }),
    ),
  );

  const stats: MineStats = { puzzles: 0, solved: 0, hardest: {} };
  const pooled = new Map<TechniqueId, Set<string>>();
  for (const result of results) {
    stats.puzzles += result.stats.puzzles;
    stats.solved += result.stats.solved;
    for (const [key, value] of Object.entries(result.stats.hardest)) {
      const k = key as keyof MineStats['hardest'];
      stats.hardest[k] = (stats.hardest[k] ?? 0) + (value ?? 0);
    }
    for (const [id, codes] of Object.entries(result.buckets)) {
      const set = pooled.get(id as TechniqueId) ?? new Set<string>();
      for (const code of codes ?? []) {
        set.add(code);
      }
      pooled.set(id as TechniqueId, set);
    }
  }

  const rng = createRng(seed);
  const positions: Record<string, string[]> = {};
  for (const technique of TECHNIQUES) {
    const codes = shuffle(rng, [...(pooled.get(technique.id) ?? [])]);
    const kept: string[] = [];
    for (const code of codes) {
      if (kept.length >= quota) {
        break;
      }
      // Re-derive rather than trust the worker: the drill contract is that this
      // technique, and nothing before it, is what moves the board on.
      const step = simplestStep(decodePosition(code), technique.id);
      if (step?.technique === technique.id) {
        kept.push(code);
      }
    }
    positions[technique.id] = kept.sort();
    console.log(`${technique.id.padEnd(18)} ${String(kept.length).padStart(3)} of ${codes.length}`);
  }

  const out = join(here, '../../src/features/girih/data/positions.json');
  const payload = {
    version: 1,
    note: 'Generated by scripts/girih/mine.ts. Each entry: 81 digits (0 = empty), then eliminated candidates as base-36 pairs of cell*9+digit-1.',
    stats: { ...stats, minutes, threads, seed },
    positions,
  };
  writeFileSync(out, `${JSON.stringify(payload, null, 1)}\n`);
  console.log(`puzzles ${stats.puzzles}, solved by the curriculum ${stats.solved} (${((100 * stats.solved) / stats.puzzles).toFixed(2)}%)`);
  console.log(`wrote ${out}`);
}
