// Glass — image upscaling that runs entirely in the browser tab.
// SPDX-License-Identifier: PolyForm-Small-Business-1.0.0
// Required Notice: Copyright 2026 Mo4n6 (https://github.com/Mo4n6/tools)
//
// The tier is the operator's choice, not the tool's. Each card states what the
// method actually does, what it costs and what it is for, because the three
// tiers are not better and worse versions of one thing: reconstructing a
// signal, preserving hard edges and inventing plausible detail are different
// jobs, and only the person looking at the image knows which one they want.

import { useCallback, useEffect, useMemo, useRef, useState } from 'react';

import { GLASS_AUTHOR, GLASS_AUTHOR_URL, GLASS_COPYRIGHT, GLASS_SOURCE_URL } from './attribution';
import { TIERS, tierById, type LocalTierId } from './pipeline';
import { usablePresets } from './presets';
import {
  DPI_CHOICES,
  DTF_PRESETS,
  FIT_MODE_COPY,
  assessPrint,
  targetPixels,
  type FitMode,
  type PrintTarget,
} from './print';
import type { TierId } from './types';
import { useGlass, type PrintSettings } from './useGlass';
import { configuredWeightsUrl, describeBytes, isUsableWeightsUrl } from './weights';

const panel = 'rounded-md border border-emerald-500/30 bg-[#07110a] p-3 text-sm text-emerald-100';
const primaryAction =
  'rounded-md border border-emerald-400 bg-emerald-500/15 px-3 py-2 text-sm text-emerald-100 hover:border-emerald-300 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-400 disabled:opacity-40';
const secondaryAction =
  'rounded-md border border-emerald-500/40 bg-[#07110a] px-3 py-2 text-sm text-emerald-100 hover:border-emerald-300/70 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-400 disabled:opacity-40';
const textField =
  'w-full rounded-md border border-emerald-500/40 bg-[#040a06] px-2 py-1.5 text-sm text-emerald-100 placeholder:text-emerald-300/30 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-400';

/**
 * Images that show what each tier is for.
 *
 * Generated by `npm run glass:samples` rather than shipped from anywhere, and
 * each is built to make one tier obviously right and the others obviously
 * wrong on it. Reading the tier descriptions is not the same as seeing the
 * difference.
 */
const SAMPLES = [
  { file: 'sprite.png', label: 'Sprite', hint: 'Hard edges and four colours. Try Pixel, then Lanczos.' },
  { file: 'chart.png', label: 'Detail', hint: 'Fine detail and a gradient. Try Lanczos, then Pixel.' },
  { file: 'soft.png', label: 'Soft', hint: 'Detail that is genuinely gone. Only Neural can invent any.' },
] as const;

type WeightsMode = 'preset' | 'file' | 'url';

const WEIGHTS_MODE_LABELS: Record<WeightsMode, string> = {
  preset: 'Known model',
  file: 'Local file',
  url: 'URL',
};

const GlassApp = (): JSX.Element => {
  const { state, load, runLocal, runNeural, cancel, clear, setPrint } = useGlass();

  const [tierId, setTierId] = useState<TierId>('lanczos');
  const [scale, setScale] = useState(2);
  const presets = useMemo(() => usablePresets(), []);
  const [weightsMode, setWeightsMode] = useState<WeightsMode>(() =>
    presets.length > 0 ? 'preset' : 'file',
  );
  const [presetId, setPresetId] = useState(() => presets[0]?.id ?? '');
  const [weightsUrl, setWeightsUrl] = useState(() => configuredWeightsUrl(import.meta.env) ?? '');
  const [weightsFile, setWeightsFile] = useState<File | null>(null);
  const [split, setSplit] = useState(50);

  const [printOn, setPrintOn] = useState(false);
  const [printTarget, setPrintTarget] = useState<PrintTarget>({
    widthInches: 11,
    heightInches: 14,
    dpi: 300,
  });
  const [fitMode, setFitMode] = useState<FitMode>('fit');

  const imageInput = useRef<HTMLInputElement | null>(null);
  // Sample clicks are ordered here rather than in the hook. The hook's guard
  // takes its number when `load` is called, which for a sample is only after
  // the fetch has finished, so two clicks race and the slower fetch wins.
  const sampleTicket = useRef(0);
  const sampleFetch = useRef<AbortController | null>(null);
  const tier = tierById(tierId);

  // Keep the factor legal for the tier: switching to Pixel while 3x is selected
  // would otherwise leave a Run button that can only fail.
  useEffect(() => {
    if (tier.scales.length > 0 && !tier.scales.includes(scale)) {
      setScale(tier.scales[0] as number);
    }
  }, [scale, tier]);

  useEffect(() => {
    setPrint(printOn ? ({ target: printTarget, mode: fitMode } satisfies PrintSettings) : null);
  }, [fitMode, printOn, printTarget, setPrint]);

  const busy = state.phase === 'running' || state.phase === 'decoding';



  const selectedPreset = presets.find((candidate) => candidate.id === presetId) ?? null;

  /**
   * What the chosen size would give, worked out before anything runs.
   *
   * The tier's own factor decides how many pixels exist; this decides how far
   * they are spread. Only the two together say whether a print will hold up,
   * and the density is the half nobody is usually shown.
   */
  const activePreset =
    DTF_PRESETS.find(
      (preset) =>
        preset.widthInches === printTarget.widthInches && preset.heightInches === printTarget.heightInches,
    ) ?? null;

  const printOutlook = useMemo(() => {
    const source = state.source;
    if (!printOn || !source) return null;

    const upscaled = {
      width: source.image.width * (tier.scales.length > 0 ? scale : (selectedPreset?.scale ?? 4)),
      height: source.image.height * (tier.scales.length > 0 ? scale : (selectedPreset?.scale ?? 4)),
    };

    try {
      const pixels = targetPixels(printTarget);
      const { dpi, quality } = assessPrint(upscaled, printTarget, fitMode);
      return { pixels, dpi: Math.round(dpi), quality, error: null as string | null };
    } catch (error) {
      return {
        pixels: null,
        dpi: 0,
        quality: 'thin' as const,
        error: error instanceof Error ? error.message : String(error),
      };
    }
  }, [fitMode, printOn, printTarget, scale, selectedPreset, state.source, tier.scales.length]);

  const weightsReady =
    weightsMode === 'preset'
      ? selectedPreset !== null
      : weightsMode === 'file'
        ? weightsFile !== null
        : isUsableWeightsUrl(weightsUrl.trim());

  const canRun =
    state.source !== null && !busy && (tierId !== 'neural' || weightsReady);

  const handleFiles = useCallback(
    (files: FileList | null) => {
      const file = files?.[0];
      if (!file) return;
      // Choosing a file also outranks any sample still being fetched.
      sampleTicket.current += 1;
      sampleFetch.current?.abort();
      sampleFetch.current = null;
      void load(file);
    },
    [load],
  );

  const loadSample = useCallback(
    async (fileName: string): Promise<void> => {
      sampleFetch.current?.abort();
      const controller = new AbortController();
      sampleFetch.current = controller;

      sampleTicket.current += 1;
      const ticket = sampleTicket.current;

      try {
        // Resolved against BASE_URL inside the handler, not at render: the
        // component is rendered to static markup in tests, where there is no
        // window to resolve against.
        const base = new URL(import.meta.env.BASE_URL, window.location.href);
        const response = await fetch(new URL(`glass-samples/${fileName}`, base).href, {
          signal: controller.signal,
        });
        if (!response.ok) return;
        const blob = await response.blob();

        // The abort above handles the common case, but a response already in
        // flight can still resolve; the ticket is what makes the newest click
        // authoritative regardless of which fetch finished first.
        if (sampleTicket.current !== ticket) return;
        await load(new File([blob], fileName, { type: blob.type || 'image/png' }));
      } catch {
        // An aborted fetch is the expected outcome of a second click, not a
        // failure worth reporting.
      }
    },
    [load],
  );

  const handleRun = useCallback(() => {
    if (tierId === 'neural') {
      if (weightsMode === 'preset' && selectedPreset) {
        // The digest travels with the URL; loadWeights refuses anything else.
        void runNeural({
          kind: 'url',
          url: selectedPreset.url,
          sha256: selectedPreset.sha256,
        });
      } else if (weightsMode === 'file' && weightsFile) {
        void runNeural({ kind: 'file', file: weightsFile });
      } else {
        void runNeural({ kind: 'url', url: weightsUrl.trim() });
      }
      return;
    }
    runLocal(tierId as LocalTierId, scale);
  }, [runLocal, runNeural, scale, selectedPreset, tierId, weightsFile, weightsMode, weightsUrl]);

  const growth = useMemo(() => {
    const source = state.source;
    const result = state.result;
    if (!source || !result) return null;
    return `${source.image.width}x${source.image.height} → ${result.width}x${result.height}`;
  }, [state.result, state.source]);

  return (
    <div className="flex w-full flex-col p-2 font-mono text-emerald-100 md:p-4">
      <header className="mb-4">
        <h1 className="text-3xl font-bold">Glass</h1>
        <p className="mt-2 max-w-3xl text-sm text-emerald-300/70">
          Enlarge an image without sending it anywhere. Three methods are offered rather than one
          chosen for you: they do genuinely different things, and the right one depends on what the
          picture is. Everything runs in this tab, and the neural tier runs weights you supply.
        </p>
      </header>

      <div className="grid gap-4 lg:grid-cols-[minmax(0,22rem)_minmax(0,1fr)]">
        <section className="flex flex-col gap-4">
          <div className={panel}>
            <div className="text-xs uppercase tracking-wide text-emerald-300/60">Source image</div>
            <input
              ref={imageInput}
              id="glass-image"
              type="file"
              accept="image/*"
              className="mt-2 block w-full text-xs text-emerald-300/70 file:mr-3 file:rounded-md file:border file:border-emerald-500/40 file:bg-emerald-500/10 file:px-2 file:py-1 file:text-xs file:text-emerald-100"
              onChange={(event) => handleFiles(event.target.files)}
            />
            {state.source ? (
              <p className="mt-2 text-xs text-emerald-300/60">
                {state.source.name} · {state.source.image.width}x{state.source.image.height} ·{' '}
                {describeBytes(state.source.byteSize)}
              </p>
            ) : (
              <p className="mt-2 text-xs text-emerald-300/40">
                Anything the browser can decode. The file is read locally and never uploaded.
              </p>
            )}

            <div className="mt-3 border-t border-emerald-500/15 pt-2">
              <div className="text-xs uppercase tracking-wide text-emerald-300/50">Or try a sample</div>
              <div className="mt-1.5 flex flex-wrap gap-2">
                {SAMPLES.map((sample) => (
                  <button
                    key={sample.file}
                    type="button"
                    title={sample.hint}
                    disabled={busy}
                    onClick={() => {
                      void loadSample(sample.file);
                    }}
                    className="rounded-md border border-emerald-500/30 px-2 py-1 text-xs hover:border-emerald-400/60 disabled:opacity-40"
                  >
                    {sample.label}
                  </button>
                ))}
              </div>
              <p className="mt-1.5 text-xs text-emerald-300/40">
                Each one makes a different tier the right answer.
              </p>
            </div>
          </div>

          <fieldset className="flex flex-col gap-2">
            <legend className="text-xs uppercase tracking-wide text-emerald-300/60">Method</legend>
            {TIERS.map((candidate) => {
              const selected = candidate.id === tierId;
              return (
                <label
                  key={candidate.id}
                  className={`cursor-pointer rounded-md border p-3 text-sm transition ${
                    selected
                      ? 'border-emerald-400 bg-emerald-500/10'
                      : 'border-emerald-500/25 bg-[#07110a] hover:border-emerald-400/50'
                  }`}
                >
                  <span className="flex items-center gap-2">
                    <input
                      type="radio"
                      name="glass-tier"
                      value={candidate.id}
                      checked={selected}
                      onChange={() => setTierId(candidate.id)}
                      className="accent-emerald-400"
                    />
                    <span className="font-semibold text-emerald-200">{candidate.label}</span>
                  </span>
                  <span className="mt-1 block text-xs text-emerald-300/70">{candidate.summary}</span>
                  <span className="mt-1 block text-xs text-emerald-300/50">
                    Best for: {candidate.bestFor}
                  </span>
                  <span className="mt-1 block text-xs text-emerald-300/50">
                    Runs on: {candidate.runsOn} · Download: {candidate.download}
                  </span>
                </label>
              );
            })}
          </fieldset>

          {tier.scales.length > 0 ? (
            <div className={panel}>
              <div className="text-xs uppercase tracking-wide text-emerald-300/60">Factor</div>
              <div className="mt-2 flex gap-2">
                {tier.scales.map((candidate) => (
                  <button
                    key={candidate}
                    type="button"
                    onClick={() => setScale(candidate)}
                    className={
                      candidate === scale
                        ? 'rounded-md border border-emerald-400 bg-emerald-500/20 px-3 py-1.5 text-sm'
                        : 'rounded-md border border-emerald-500/30 px-3 py-1.5 text-sm hover:border-emerald-400/60'
                    }
                  >
                    {candidate}x
                  </button>
                ))}
              </div>
            </div>
          ) : (
            <div className={panel}>
              <div className="text-xs uppercase tracking-wide text-emerald-300/60">Weights</div>
              <p className="mt-1 text-xs text-emerald-300/60">
                {presets.length > 0
                  ? 'Glass ships no model, but it knows where a few live. Pick one below, or supply your own file or URL. Either way the factor comes from the model itself.'
                  : 'Glass ships no model. Point it at an ONNX super-resolution network — an ESRGAN-family export is the usual choice — and the factor comes from the model itself. No known models are configured yet; add one with npm run glass:preset.'}
              </p>

              <div className="mt-3 flex gap-2 text-xs">
                {(presets.length > 0 ? (['preset', 'file', 'url'] as const) : (['file', 'url'] as const)).map(
                  (mode) => (
                    <button
                      key={mode}
                      type="button"
                      onClick={() => setWeightsMode(mode)}
                      className={
                        mode === weightsMode
                          ? 'rounded-md border border-emerald-400 bg-emerald-500/20 px-2 py-1'
                          : 'rounded-md border border-emerald-500/30 px-2 py-1 hover:border-emerald-400/60'
                      }
                    >
                      {WEIGHTS_MODE_LABELS[mode]}
                    </button>
                  ),
                )}
              </div>

              {weightsMode === 'preset' ? (
                presets.length > 0 ? (
                  <>
                    <select
                      value={presetId}
                      onChange={(event) => setPresetId(event.target.value)}
                      className={`mt-2 ${textField}`}
                      aria-label="Known model"
                    >
                      {presets.map((preset) => (
                        <option key={preset.id} value={preset.id}>
                          {preset.label} — {preset.scale}x
                          {preset.bytes === undefined ? '' : `, ${describeBytes(preset.bytes)}`}
                        </option>
                      ))}
                    </select>
                    {selectedPreset ? (
                      <p className="mt-1 text-xs text-emerald-300/60">{selectedPreset.note}</p>
                    ) : null}
                    <p className="mt-1 text-xs text-emerald-300/40">
                      Pinned to one revision and checked against a recorded SHA-256 before the model
                      is loaded. Bytes that do not match are refused, so the host serving them does
                      not have to be trusted.
                    </p>
                  </>
                ) : (
                  <p className="mt-2 text-xs text-emerald-300/40">No known models are configured.</p>
                )
              ) : weightsMode === 'file' ? (
                <input
                  type="file"
                  accept=".onnx,application/octet-stream"
                  className="mt-2 block w-full text-xs text-emerald-300/70 file:mr-3 file:rounded-md file:border file:border-emerald-500/40 file:bg-emerald-500/10 file:px-2 file:py-1 file:text-xs file:text-emerald-100"
                  onChange={(event) => setWeightsFile(event.target.files?.[0] ?? null)}
                />
              ) : (
                <>
                  <input
                    type="url"
                    value={weightsUrl}
                    onChange={(event) => setWeightsUrl(event.target.value)}
                    placeholder="https://…/model.onnx"
                    className={`mt-2 ${textField}`}
                  />
                  <p className="mt-1 text-xs text-emerald-300/40">
                    Fetched by your browser, cached after the first load. https only, except on
                    localhost.
                  </p>
                </>
              )}
            </div>
          )}

          <div className={panel}>
            <label className="flex cursor-pointer items-center gap-2 text-xs uppercase tracking-wide text-emerald-300/60">
              <input
                type="checkbox"
                checked={printOn}
                onChange={(event) => setPrintOn(event.target.checked)}
                className="accent-emerald-400"
              />
              Print size
            </label>

            {printOn ? (
              <>
                <p className="mt-1 text-xs text-emerald-300/50">
                  The tier decides how much detail there is; this decides how far it is spread.
                  Fitted after upscaling, and padded with transparency so no ink is printed around it.
                </p>

                <div className="mt-2 flex flex-wrap gap-1.5">
                  {DTF_PRESETS.map((preset) => {
                    const active =
                      preset.widthInches === printTarget.widthInches &&
                      preset.heightInches === printTarget.heightInches;
                    return (
                      <button
                        key={preset.id}
                        type="button"
                        title={preset.note}
                        onClick={() =>
                          setPrintTarget((previous) => ({
                            ...previous,
                            widthInches: preset.widthInches,
                            heightInches: preset.heightInches,
                          }))
                        }
                        className={
                          active
                            ? 'rounded-md border border-emerald-400 bg-emerald-500/20 px-2 py-1 text-xs'
                            : 'rounded-md border border-emerald-500/30 px-2 py-1 text-xs hover:border-emerald-400/60'
                        }
                      >
                        {preset.widthInches}x{preset.heightInches}
                      </button>
                    );
                  })}
                </div>

                {activePreset ? (
                  <p className="mt-1 text-xs text-emerald-300/50">{activePreset.note}</p>
                ) : null}

                <div className="mt-2 grid grid-cols-3 gap-2">
                  {(
                    [
                      ['Width in', 'widthInches'],
                      ['Height in', 'heightInches'],
                    ] as const
                  ).map(([label, key]) => (
                    <label key={key} className="text-xs text-emerald-300/50">
                      {label}
                      <input
                        type="number"
                        min={0.25}
                        max={120}
                        step={0.25}
                        value={printTarget[key]}
                        onChange={(event) =>
                          setPrintTarget((previous) => ({
                            ...previous,
                            [key]: Math.max(0.25, Number(event.target.value) || 0.25),
                          }))
                        }
                        className={`mt-1 ${textField}`}
                      />
                    </label>
                  ))}
                  <label className="text-xs text-emerald-300/50">
                    DPI
                    <select
                      value={printTarget.dpi}
                      onChange={(event) =>
                        setPrintTarget((previous) => ({ ...previous, dpi: Number(event.target.value) }))
                      }
                      className={`mt-1 ${textField}`}
                    >
                      {DPI_CHOICES.map((dpi) => (
                        <option key={dpi} value={dpi}>
                          {dpi}
                        </option>
                      ))}
                    </select>
                  </label>
                </div>

                <div className="mt-2 flex gap-2 text-xs">
                  {(['fit', 'fill'] as const).map((mode) => (
                    <button
                      key={mode}
                      type="button"
                      title={FIT_MODE_COPY[mode].description}
                      onClick={() => setFitMode(mode)}
                      className={
                        mode === fitMode
                          ? 'rounded-md border border-emerald-400 bg-emerald-500/20 px-2 py-1'
                          : 'rounded-md border border-emerald-500/30 px-2 py-1 hover:border-emerald-400/60'
                      }
                    >
                      {FIT_MODE_COPY[mode].label}
                    </button>
                  ))}
                </div>
                <p className="mt-1 text-xs text-emerald-300/60">{FIT_MODE_COPY[fitMode].description}</p>

                {printOutlook ? (
                  printOutlook.error ? (
                    <p className="mt-2 text-xs text-rose-300/80">{printOutlook.error}</p>
                  ) : (
                    <p className="mt-2 text-xs text-emerald-300/60">
                      {printOutlook.pixels?.width}x{printOutlook.pixels?.height} px ·{' '}
                      <span
                        className={
                          printOutlook.quality === 'thin'
                            ? 'text-rose-300'
                            : printOutlook.quality === 'marginal'
                              ? 'text-amber-300'
                              : 'text-emerald-200'
                        }
                      >
                        {printOutlook.dpi} DPI, {printOutlook.quality}
                      </span>
                    </p>
                  )
                ) : (
                  <p className="mt-2 text-xs text-emerald-300/40">Choose an image to see the density.</p>
                )}
              </>
            ) : null}
          </div>

          <div className="flex gap-2">
            <button type="button" className={primaryAction} disabled={!canRun} onClick={handleRun}>
              Upscale
            </button>
            <button type="button" className={secondaryAction} disabled={!busy} onClick={cancel}>
              Cancel
            </button>
            <button
              type="button"
              className={secondaryAction}
              disabled={!state.source && !state.result}
              onClick={() => {
                clear();
                if (imageInput.current) imageInput.current.value = '';
              }}
            >
              Clear
            </button>
          </div>

          {state.progress ? (
            <div className={panel} role="status" aria-live="polite">
              <div className="flex justify-between text-xs text-emerald-300/70">
                <span>{state.progress.note}</span>
                {state.progress.fraction !== null ? (
                  <span>{Math.round(state.progress.fraction * 100)}%</span>
                ) : null}
              </div>
              <div className="mt-2 h-1 w-full overflow-hidden rounded bg-emerald-500/15">
                <div
                  className="h-full bg-emerald-400 transition-all"
                  style={{ width: `${Math.round((state.progress.fraction ?? 0.04) * 100)}%` }}
                />
              </div>
            </div>
          ) : null}

          {state.error ? (
            <div className="rounded-md border border-rose-500/40 bg-[#150808] p-3 text-sm text-rose-200">
              {state.error}
            </div>
          ) : null}
        </section>

        <section className="flex flex-col gap-3">
          {state.result && state.source ? (
            <>
              <div className="relative select-none overflow-hidden rounded-md border border-emerald-500/30 bg-[#040a06]">
                <img
                  src={state.source.previewUrl}
                  alt="Source"
                  className="block w-full"
                  style={{ imageRendering: 'pixelated' }}
                />
                <img
                  src={state.result.url}
                  alt="Upscaled result"
                  className="absolute inset-0 block h-full w-full"
                  style={{ clipPath: `inset(0 0 0 ${split}%)` }}
                />
                <div
                  className="pointer-events-none absolute inset-y-0 w-px bg-emerald-400"
                  style={{ left: `${split}%` }}
                />
              </div>

              <label className="flex items-center gap-3 text-xs text-emerald-300/60">
                <span className="shrink-0">Source</span>
                <input
                  type="range"
                  min={0}
                  max={100}
                  value={split}
                  onChange={(event) => setSplit(Number(event.target.value))}
                  className="w-full accent-emerald-400"
                  aria-label="Comparison split"
                />
                <span className="shrink-0">Result</span>
              </label>

              <div className={panel}>
                <dl className="grid grid-cols-2 gap-x-4 gap-y-1 text-xs">
                  <dt className="text-emerald-300/50">Method</dt>
                  <dd>{tierById(state.result.tier).label}</dd>
                  <dt className="text-emerald-300/50">Size</dt>
                  <dd>{growth}</dd>
                  <dt className="text-emerald-300/50">Factor</dt>
                  <dd>{state.result.scale.toFixed(2).replace(/\.00$/, '')}x</dd>
                  <dt className="text-emerald-300/50">Elapsed</dt>
                  <dd>{(state.result.elapsedMs / 1000).toFixed(2)}s</dd>
                  <dt className="text-emerald-300/50">PNG</dt>
                  <dd>{describeBytes(state.result.byteSize)}</dd>
                  {state.result.backend ? (
                    <>
                      <dt className="text-emerald-300/50">Backend</dt>
                      <dd>{state.result.backend}</dd>
                    </>
                  ) : null}
                </dl>
                <a
                  className={`mt-3 inline-block ${primaryAction}`}
                  href={state.result.url}
                  download={state.result.fileName}
                >
                  Download {state.result.fileName}
                </a>
              </div>
            </>
          ) : state.source ? (
            <div className="overflow-hidden rounded-md border border-emerald-500/30 bg-[#040a06]">
              <img src={state.source.previewUrl} alt="Source" className="block w-full" />
            </div>
          ) : (
            <div className="flex min-h-48 items-center justify-center rounded-md border border-dashed border-emerald-500/25 p-6 text-center text-sm text-emerald-300/40">
              Choose an image to begin.
            </div>
          )}
        </section>
      </div>

      <footer className="mt-6 border-t border-emerald-500/20 pt-3 text-xs text-emerald-300/40">
        {GLASS_COPYRIGHT} ·{' '}
        <a className="underline hover:text-emerald-300/70" href={GLASS_AUTHOR_URL}>
          @{GLASS_AUTHOR}
        </a>{' '}
        ·{' '}
        <a className="underline hover:text-emerald-300/70" href={GLASS_SOURCE_URL}>
          source
        </a>
      </footer>
    </div>
  );
};

export default GlassApp;
