export type ValuationStatus = 'automated' | 'stale' | 'not_applicable' | 'error';

export type GeneratedValuationRow = {
  ticker: string;
  status: ValuationStatus;
  assetClass: 'equity' | 'real_estate' | 'non_earnings';
  provider: string | null;
  sourceUrl: string | null;
  proxyTicker?: string | null;
  asOf: string;
  primaryMetric: string | null;
  primaryMultiple: number | null;
  benchmarkMultiple: number | null;
  primaryRelative: number | null;
  priceToBook: number | null;
  benchmarkPriceToBook: number | null;
  pbRelative: number | null;
  crossSectionScore: number | null;
  trackedHistoryPercentile: number | null;
  historySamples: number;
  valueScore: number | null;
  note: string;
};

export const valuationDataMeta = {
  "generatedAt": "2026-09-30T02:17:58Z",
  "benchmark": "SPY",
  "minimumHistorySamples": 20,
  "automatedTickers": [
    "EEM",
    "EFA",
    "IWM",
    "IYR",
    "SMH",
    "XLB",
    "XLE",
    "XLF",
    "XLI",
    "XLK",
    "XLU",
    "XLV"
  ],
  "notApplicableTickers": [
    "GLD",
    "KMLM",
    "PDBC",
    "TLT",
    "UUP"
  ],
  "providers": [
    "State Street",
    "iShares"
  ],
  "note": "Equity/real-estate valuation is automated from official sponsor pages. SMH uses SOXX as a clearly labeled semiconductor-sector valuation proxy. Non-earnings assets are intentionally not assigned P/E-style value scores."
} as const;

export const valuationRows: GeneratedValuationRow[] = [
  {
    "ticker": "EEM",
    "status": "automated",
    "assetClass": "equity",
    "provider": "iShares",
    "sourceUrl": "https://www.ishares.com/us/products/239637/ishares-msci-emerging-markets-etf",
    "proxyTicker": null,
    "asOf": "2026-09-28",
    "primaryMetric": "P/E",
    "primaryMultiple": 19.87,
    "benchmarkMultiple": 25.03,
    "primaryRelative": 0.7938,
    "priceToBook": 2.74,
    "benchmarkPriceToBook": 5.33,
    "pbRelative": 0.5141,
    "crossSectionScore": 80.4,
    "trackedHistoryPercentile": null,
    "historySamples": 5,
    "valueScore": 80.4,
    "note": "Sponsor fundamentals are as of 2026-09-28. Value score blends the ETF's primary valuation multiple and P/B versus SPY. Tracked-history percentile activates after 20 samples; currently 5."
  },
  {
    "ticker": "EFA",
    "status": "automated",
    "assetClass": "equity",
    "provider": "iShares",
    "sourceUrl": "https://www.ishares.com/us/products/239623/ishares-msci-eafe-etf",
    "proxyTicker": null,
    "asOf": "2026-09-28",
    "primaryMetric": "P/E",
    "primaryMultiple": 19.21,
    "benchmarkMultiple": 25.03,
    "primaryRelative": 0.7675,
    "priceToBook": 2.37,
    "benchmarkPriceToBook": 5.33,
    "pbRelative": 0.4447,
    "crossSectionScore": 82.6,
    "trackedHistoryPercentile": null,
    "historySamples": 5,
    "valueScore": 82.6,
    "note": "Sponsor fundamentals are as of 2026-09-28. Value score blends the ETF's primary valuation multiple and P/B versus SPY. Tracked-history percentile activates after 20 samples; currently 5."
  },
  {
    "ticker": "GLD",
    "status": "not_applicable",
    "assetClass": "non_earnings",
    "provider": null,
    "sourceUrl": null,
    "proxyTicker": null,
    "asOf": "2026-09-30",
    "primaryMetric": null,
    "primaryMultiple": null,
    "benchmarkMultiple": null,
    "primaryRelative": null,
    "priceToBook": null,
    "benchmarkPriceToBook": null,
    "pbRelative": null,
    "crossSectionScore": null,
    "trackedHistoryPercentile": null,
    "historySamples": 0,
    "valueScore": null,
    "note": "Gold does not have an earnings multiple comparable with SPY."
  },
  {
    "ticker": "IWM",
    "status": "automated",
    "assetClass": "equity",
    "provider": "iShares",
    "sourceUrl": "https://www.ishares.com/us/products/239710/ishares-russell-2000-etf",
    "proxyTicker": null,
    "asOf": "2026-09-28",
    "primaryMetric": "P/E",
    "primaryMultiple": 18.16,
    "benchmarkMultiple": 25.03,
    "primaryRelative": 0.7255,
    "priceToBook": 2.1,
    "benchmarkPriceToBook": 5.33,
    "pbRelative": 0.394,
    "crossSectionScore": 85.3,
    "trackedHistoryPercentile": null,
    "historySamples": 5,
    "valueScore": 85.3,
    "note": "Sponsor fundamentals are as of 2026-09-28. Value score blends the ETF's primary valuation multiple and P/B versus SPY. Tracked-history percentile activates after 20 samples; currently 5."
  },
  {
    "ticker": "IYR",
    "status": "automated",
    "assetClass": "real_estate",
    "provider": "iShares",
    "sourceUrl": "https://www.ishares.com/us/products/239520/ishares-us-real-estate-etf",
    "proxyTicker": null,
    "asOf": "2026-09-28",
    "primaryMetric": "P/CF",
    "primaryMultiple": 16.42,
    "benchmarkMultiple": 18.29,
    "primaryRelative": 0.8978,
    "priceToBook": 2.43,
    "benchmarkPriceToBook": 5.33,
    "pbRelative": 0.4559,
    "crossSectionScore": 74.1,
    "trackedHistoryPercentile": null,
    "historySamples": 5,
    "valueScore": 74.1,
    "note": "Sponsor fundamentals are as of 2026-09-28. Value score blends the ETF's primary valuation multiple and P/B versus SPY. Tracked-history percentile activates after 20 samples; currently 5."
  },
  {
    "ticker": "KMLM",
    "status": "not_applicable",
    "assetClass": "non_earnings",
    "provider": null,
    "sourceUrl": null,
    "proxyTicker": null,
    "asOf": "2026-09-30",
    "primaryMetric": null,
    "primaryMultiple": null,
    "benchmarkMultiple": null,
    "primaryRelative": null,
    "priceToBook": null,
    "benchmarkPriceToBook": null,
    "pbRelative": null,
    "crossSectionScore": null,
    "trackedHistoryPercentile": null,
    "historySamples": 0,
    "valueScore": null,
    "note": "Managed futures do not have an earnings multiple comparable with SPY."
  },
  {
    "ticker": "PDBC",
    "status": "not_applicable",
    "assetClass": "non_earnings",
    "provider": null,
    "sourceUrl": null,
    "proxyTicker": null,
    "asOf": "2026-09-30",
    "primaryMetric": null,
    "primaryMultiple": null,
    "benchmarkMultiple": null,
    "primaryRelative": null,
    "priceToBook": null,
    "benchmarkPriceToBook": null,
    "pbRelative": null,
    "crossSectionScore": null,
    "trackedHistoryPercentile": null,
    "historySamples": 0,
    "valueScore": null,
    "note": "Broad commodities do not have an earnings multiple comparable with SPY."
  },
  {
    "ticker": "SMH",
    "status": "automated",
    "assetClass": "equity",
    "provider": "iShares",
    "sourceUrl": "https://www.ishares.com/us/products/239705/ishares-semiconductor-etf",
    "proxyTicker": "SOXX",
    "asOf": "2026-09-28",
    "primaryMetric": "P/E",
    "primaryMultiple": 68.95,
    "benchmarkMultiple": 25.03,
    "primaryRelative": 2.7547,
    "priceToBook": 11.96,
    "benchmarkPriceToBook": 5.33,
    "pbRelative": 2.2439,
    "crossSectionScore": 0.0,
    "trackedHistoryPercentile": null,
    "historySamples": 5,
    "valueScore": 0.0,
    "note": "Valuation proxy: SOXX is used for the semiconductor complex because the SMH sponsor endpoint blocks automated CI access. Sponsor fundamentals are as of 2026-09-28. Value score blends the ETF's primary valuation multiple and P/B versus SPY. Tracked-history percentile activates after 20 samples; currently 5."
  },
  {
    "ticker": "TLT",
    "status": "not_applicable",
    "assetClass": "non_earnings",
    "provider": null,
    "sourceUrl": null,
    "proxyTicker": null,
    "asOf": "2026-09-30",
    "primaryMetric": null,
    "primaryMultiple": null,
    "benchmarkMultiple": null,
    "primaryRelative": null,
    "priceToBook": null,
    "benchmarkPriceToBook": null,
    "pbRelative": null,
    "crossSectionScore": null,
    "trackedHistoryPercentile": null,
    "historySamples": 0,
    "valueScore": null,
    "note": "Long-duration Treasuries are better valued with yield/term-premium measures than P/E."
  },
  {
    "ticker": "UUP",
    "status": "not_applicable",
    "assetClass": "non_earnings",
    "provider": null,
    "sourceUrl": null,
    "proxyTicker": null,
    "asOf": "2026-09-30",
    "primaryMetric": null,
    "primaryMultiple": null,
    "benchmarkMultiple": null,
    "primaryRelative": null,
    "priceToBook": null,
    "benchmarkPriceToBook": null,
    "pbRelative": null,
    "crossSectionScore": null,
    "trackedHistoryPercentile": null,
    "historySamples": 0,
    "valueScore": null,
    "note": "A currency index does not have an earnings multiple comparable with SPY."
  },
  {
    "ticker": "XLB",
    "status": "automated",
    "assetClass": "equity",
    "provider": "State Street",
    "sourceUrl": "https://www.ssga.com/us/en/intermediary/etfs/state-street-materials-select-sector-spdr-etf-xlb",
    "proxyTicker": null,
    "asOf": "2026-09-28",
    "primaryMetric": "Forward P/E (FY1)",
    "primaryMultiple": 16.94,
    "benchmarkMultiple": 21.23,
    "primaryRelative": 0.7979,
    "priceToBook": 2.72,
    "benchmarkPriceToBook": 5.33,
    "pbRelative": 0.5103,
    "crossSectionScore": 80.3,
    "trackedHistoryPercentile": null,
    "historySamples": 5,
    "valueScore": 80.3,
    "note": "Sponsor fundamentals are as of 2026-09-28. Value score blends the ETF's primary valuation multiple and P/B versus SPY. Tracked-history percentile activates after 20 samples; currently 5."
  },
  {
    "ticker": "XLE",
    "status": "automated",
    "assetClass": "equity",
    "provider": "State Street",
    "sourceUrl": "https://www.ssga.com/us/en/intermediary/etfs/state-street-energy-select-sector-spdr-etf-xle",
    "proxyTicker": null,
    "asOf": "2026-09-28",
    "primaryMetric": "Forward P/E (FY1)",
    "primaryMultiple": 12.15,
    "benchmarkMultiple": 21.23,
    "primaryRelative": 0.5723,
    "priceToBook": 2.51,
    "benchmarkPriceToBook": 5.33,
    "pbRelative": 0.4709,
    "crossSectionScore": 95.3,
    "trackedHistoryPercentile": null,
    "historySamples": 5,
    "valueScore": 95.3,
    "note": "Sponsor fundamentals are as of 2026-09-28. Value score blends the ETF's primary valuation multiple and P/B versus SPY. Tracked-history percentile activates after 20 samples; currently 5."
  },
  {
    "ticker": "XLF",
    "status": "automated",
    "assetClass": "equity",
    "provider": "State Street",
    "sourceUrl": "https://www.ssga.com/us/en/intermediary/etfs/state-street-financial-select-sector-spdr-etf-xlf",
    "proxyTicker": null,
    "asOf": "2026-09-28",
    "primaryMetric": "Forward P/E (FY1)",
    "primaryMultiple": 15.21,
    "benchmarkMultiple": 21.23,
    "primaryRelative": 0.7164,
    "priceToBook": 2.3,
    "benchmarkPriceToBook": 5.33,
    "pbRelative": 0.4315,
    "crossSectionScore": 85.9,
    "trackedHistoryPercentile": null,
    "historySamples": 5,
    "valueScore": 85.9,
    "note": "Sponsor fundamentals are as of 2026-09-28. Value score blends the ETF's primary valuation multiple and P/B versus SPY. Tracked-history percentile activates after 20 samples; currently 5."
  },
  {
    "ticker": "XLI",
    "status": "automated",
    "assetClass": "equity",
    "provider": "State Street",
    "sourceUrl": "https://www.ssga.com/us/en/intermediary/etfs/state-street-industrial-select-sector-spdr-etf-xli",
    "proxyTicker": null,
    "asOf": "2026-09-28",
    "primaryMetric": "Forward P/E (FY1)",
    "primaryMultiple": 24.64,
    "benchmarkMultiple": 21.23,
    "primaryRelative": 1.1606,
    "priceToBook": 6.65,
    "benchmarkPriceToBook": 5.33,
    "pbRelative": 1.2477,
    "crossSectionScore": 30.9,
    "trackedHistoryPercentile": null,
    "historySamples": 5,
    "valueScore": 30.9,
    "note": "Sponsor fundamentals are as of 2026-09-28. Value score blends the ETF's primary valuation multiple and P/B versus SPY. Tracked-history percentile activates after 20 samples; currently 5."
  },
  {
    "ticker": "XLK",
    "status": "automated",
    "assetClass": "equity",
    "provider": "State Street",
    "sourceUrl": "https://www.ssga.com/us/en/intermediary/etfs/state-street-technology-select-sector-spdr-etf-xlk",
    "proxyTicker": null,
    "asOf": "2026-09-28",
    "primaryMetric": "Forward P/E (FY1)",
    "primaryMultiple": 27.21,
    "benchmarkMultiple": 21.23,
    "primaryRelative": 1.2817,
    "priceToBook": 12.38,
    "benchmarkPriceToBook": 5.33,
    "pbRelative": 2.3227,
    "crossSectionScore": 14.2,
    "trackedHistoryPercentile": null,
    "historySamples": 5,
    "valueScore": 14.2,
    "note": "Sponsor fundamentals are as of 2026-09-28. Value score blends the ETF's primary valuation multiple and P/B versus SPY. Tracked-history percentile activates after 20 samples; currently 5."
  },
  {
    "ticker": "XLU",
    "status": "automated",
    "assetClass": "equity",
    "provider": "State Street",
    "sourceUrl": "https://www.ssga.com/us/en/intermediary/etfs/state-street-utilities-select-sector-spdr-etf-xlu",
    "proxyTicker": null,
    "asOf": "2026-09-28",
    "primaryMetric": "Forward P/E (FY1)",
    "primaryMultiple": 16.41,
    "benchmarkMultiple": 21.23,
    "primaryRelative": 0.773,
    "priceToBook": 2.0,
    "benchmarkPriceToBook": 5.33,
    "pbRelative": 0.3752,
    "crossSectionScore": 82.3,
    "trackedHistoryPercentile": null,
    "historySamples": 5,
    "valueScore": 82.3,
    "note": "Sponsor fundamentals are as of 2026-09-28. Value score blends the ETF's primary valuation multiple and P/B versus SPY. Tracked-history percentile activates after 20 samples; currently 5."
  },
  {
    "ticker": "XLV",
    "status": "automated",
    "assetClass": "equity",
    "provider": "State Street",
    "sourceUrl": "https://www.ssga.com/us/en/intermediary/etfs/state-street-health-care-select-sector-spdr-etf-xlv",
    "proxyTicker": null,
    "asOf": "2026-09-28",
    "primaryMetric": "Forward P/E (FY1)",
    "primaryMultiple": 20.44,
    "benchmarkMultiple": 21.23,
    "primaryRelative": 0.9628,
    "priceToBook": 4.84,
    "benchmarkPriceToBook": 5.33,
    "pbRelative": 0.9081,
    "crossSectionScore": 55.6,
    "trackedHistoryPercentile": null,
    "historySamples": 5,
    "valueScore": 55.6,
    "note": "Sponsor fundamentals are as of 2026-09-28. Value score blends the ETF's primary valuation multiple and P/B versus SPY. Tracked-history percentile activates after 20 samples; currently 5."
  }
];
