export type ValuationStatus = 'automated' | 'stale' | 'not_applicable' | 'error';

export type GeneratedValuationRow = {
  ticker: string;
  status: ValuationStatus;
  assetClass: 'equity' | 'real_estate' | 'non_earnings';
  provider: string | null;
  sourceUrl: string | null;
  proxyTicker?: string | null;
  asOf: string;
  primaryMetric: string | null;
  primaryMultiple: number | null;
  benchmarkMultiple: number | null;
  primaryRelative: number | null;
  priceToBook: number | null;
  benchmarkPriceToBook: number | null;
  pbRelative: number | null;
  crossSectionScore: number | null;
  trackedHistoryPercentile: number | null;
  historySamples: number;
  valueScore: number | null;
  note: string;
};

export const valuationDataMeta = {
  "generatedAt": "2026-10-07T02:37:45Z",
  "benchmark": "SPY",
  "minimumHistorySamples": 20,
  "automatedTickers": [
    "EEM",
    "EFA",
    "IWM",
    "IYR",
    "SMH",
    "XLB",
    "XLE",
    "XLF",
    "XLI",
    "XLK",
    "XLU",
    "XLV"
  ],
  "notApplicableTickers": [
    "GLD",
    "KMLM",
    "PDBC",
    "TLT",
    "UUP"
  ],
  "providers": [
    "State Street",
    "iShares"
  ],
  "note": "Equity/real-estate valuation is automated from official sponsor pages. SMH uses SOXX as a clearly labeled semiconductor-sector valuation proxy. Non-earnings assets are intentionally not assigned P/E-style value scores."
} as const;

export const valuationRows: GeneratedValuationRow[] = [
  {
    "ticker": "EEM",
    "status": "automated",
    "assetClass": "equity",
    "provider": "iShares",
    "sourceUrl": "https://www.ishares.com/us/products/239637/ishares-msci-emerging-markets-etf",
    "proxyTicker": null,
    "asOf": "2026-10-05",
    "primaryMetric": "P/E",
    "primaryMultiple": 19.8,
    "benchmarkMultiple": 24.98,
    "primaryRelative": 0.7926,
    "priceToBook": 2.75,
    "benchmarkPriceToBook": 5.41,
    "pbRelative": 0.5083,
    "crossSectionScore": 80.7,
    "trackedHistoryPercentile": null,
    "historySamples": 10,
    "valueScore": 80.7,
    "note": "Sponsor fundamentals are as of 2026-10-05. Value score blends the ETF's primary valuation multiple and P/B versus SPY. Tracked-history percentile activates after 20 samples; currently 10."
  },
  {
    "ticker": "EFA",
    "status": "automated",
    "assetClass": "equity",
    "provider": "iShares",
    "sourceUrl": "https://www.ishares.com/us/products/239623/ishares-msci-eafe-etf",
    "proxyTicker": null,
    "asOf": "2026-10-05",
    "primaryMetric": "P/E",
    "primaryMultiple": 18.98,
    "benchmarkMultiple": 24.98,
    "primaryRelative": 0.7598,
    "priceToBook": 2.35,
    "benchmarkPriceToBook": 5.41,
    "pbRelative": 0.4344,
    "crossSectionScore": 83.1,
    "trackedHistoryPercentile": null,
    "historySamples": 10,
    "valueScore": 83.1,
    "note": "Sponsor fundamentals are as of 2026-10-05. Value score blends the ETF's primary valuation multiple and P/B versus SPY. Tracked-history percentile activates after 20 samples; currently 10."
  },
  {
    "ticker": "GLD",
    "status": "not_applicable",
    "assetClass": "non_earnings",
    "provider": null,
    "sourceUrl": null,
    "proxyTicker": null,
    "asOf": "2026-10-07",
    "primaryMetric": null,
    "primaryMultiple": null,
    "benchmarkMultiple": null,
    "primaryRelative": null,
    "priceToBook": null,
    "benchmarkPriceToBook": null,
    "pbRelative": null,
    "crossSectionScore": null,
    "trackedHistoryPercentile": null,
    "historySamples": 0,
    "valueScore": null,
    "note": "Gold does not have an earnings multiple comparable with SPY."
  },
  {
    "ticker": "IWM",
    "status": "automated",
    "assetClass": "equity",
    "provider": "iShares",
    "sourceUrl": "https://www.ishares.com/us/products/239710/ishares-russell-2000-etf",
    "proxyTicker": null,
    "asOf": "2026-10-05",
    "primaryMetric": "P/E",
    "primaryMultiple": 18.05,
    "benchmarkMultiple": 24.98,
    "primaryRelative": 0.7226,
    "priceToBook": 2.09,
    "benchmarkPriceToBook": 5.41,
    "pbRelative": 0.3863,
    "crossSectionScore": 85.5,
    "trackedHistoryPercentile": null,
    "historySamples": 10,
    "valueScore": 85.5,
    "note": "Sponsor fundamentals are as of 2026-10-05. Value score blends the ETF's primary valuation multiple and P/B versus SPY. Tracked-history percentile activates after 20 samples; currently 10."
  },
  {
    "ticker": "IYR",
    "status": "automated",
    "assetClass": "real_estate",
    "provider": "iShares",
    "sourceUrl": "https://www.ishares.com/us/products/239520/ishares-us-real-estate-etf",
    "proxyTicker": null,
    "asOf": "2026-10-05",
    "primaryMetric": "P/CF",
    "primaryMultiple": 16.01,
    "benchmarkMultiple": 18.52,
    "primaryRelative": 0.8645,
    "priceToBook": 2.37,
    "benchmarkPriceToBook": 5.41,
    "pbRelative": 0.4381,
    "crossSectionScore": 76.3,
    "trackedHistoryPercentile": null,
    "historySamples": 10,
    "valueScore": 76.3,
    "note": "Sponsor fundamentals are as of 2026-10-05. Value score blends the ETF's primary valuation multiple and P/B versus SPY. Tracked-history percentile activates after 20 samples; currently 10."
  },
  {
    "ticker": "KMLM",
    "status": "not_applicable",
    "assetClass": "non_earnings",
    "provider": null,
    "sourceUrl": null,
    "proxyTicker": null,
    "asOf": "2026-10-07",
    "primaryMetric": null,
    "primaryMultiple": null,
    "benchmarkMultiple": null,
    "primaryRelative": null,
    "priceToBook": null,
    "benchmarkPriceToBook": null,
    "pbRelative": null,
    "crossSectionScore": null,
    "trackedHistoryPercentile": null,
    "historySamples": 0,
    "valueScore": null,
    "note": "Managed futures do not have an earnings multiple comparable with SPY."
  },
  {
    "ticker": "PDBC",
    "status": "not_applicable",
    "assetClass": "non_earnings",
    "provider": null,
    "sourceUrl": null,
    "proxyTicker": null,
    "asOf": "2026-10-07",
    "primaryMetric": null,
    "primaryMultiple": null,
    "benchmarkMultiple": null,
    "primaryRelative": null,
    "priceToBook": null,
    "benchmarkPriceToBook": null,
    "pbRelative": null,
    "crossSectionScore": null,
    "trackedHistoryPercentile": null,
    "historySamples": 0,
    "valueScore": null,
    "note": "Broad commodities do not have an earnings multiple comparable with SPY."
  },
  {
    "ticker": "SMH",
    "status": "automated",
    "assetClass": "equity",
    "provider": "iShares",
    "sourceUrl": "https://www.ishares.com/us/products/239705/ishares-semiconductor-etf",
    "proxyTicker": "SOXX",
    "asOf": "2026-10-05",
    "primaryMetric": "P/E",
    "primaryMultiple": 51.76,
    "benchmarkMultiple": 24.98,
    "primaryRelative": 2.0721,
    "priceToBook": 11.54,
    "benchmarkPriceToBook": 5.41,
    "pbRelative": 2.1331,
    "crossSectionScore": 0.0,
    "trackedHistoryPercentile": null,
    "historySamples": 10,
    "valueScore": 0.0,
    "note": "Valuation proxy: SOXX is used for the semiconductor complex because the SMH sponsor endpoint blocks automated CI access. Sponsor fundamentals are as of 2026-10-05. Value score blends the ETF's primary valuation multiple and P/B versus SPY. Tracked-history percentile activates after 20 samples; currently 10."
  },
  {
    "ticker": "TLT",
    "status": "not_applicable",
    "assetClass": "non_earnings",
    "provider": null,
    "sourceUrl": null,
    "proxyTicker": null,
    "asOf": "2026-10-07",
    "primaryMetric": null,
    "primaryMultiple": null,
    "benchmarkMultiple": null,
    "primaryRelative": null,
    "priceToBook": null,
    "benchmarkPriceToBook": null,
    "pbRelative": null,
    "crossSectionScore": null,
    "trackedHistoryPercentile": null,
    "historySamples": 0,
    "valueScore": null,
    "note": "Long-duration Treasuries are better valued with yield/term-premium measures than P/E."
  },
  {
    "ticker": "UUP",
    "status": "not_applicable",
    "assetClass": "non_earnings",
    "provider": null,
    "sourceUrl": null,
    "proxyTicker": null,
    "asOf": "2026-10-07",
    "primaryMetric": null,
    "primaryMultiple": null,
    "benchmarkMultiple": null,
    "primaryRelative": null,
    "priceToBook": null,
    "benchmarkPriceToBook": null,
    "pbRelative": null,
    "crossSectionScore": null,
    "trackedHistoryPercentile": null,
    "historySamples": 0,
    "valueScore": null,
    "note": "A currency index does not have an earnings multiple comparable with SPY."
  },
  {
    "ticker": "XLB",
    "status": "automated",
    "assetClass": "equity",
    "provider": "State Street",
    "sourceUrl": "https://www.ssga.com/us/en/intermediary/etfs/state-street-materials-select-sector-spdr-etf-xlb",
    "proxyTicker": null,
    "asOf": "2026-10-05",
    "primaryMetric": "Forward P/E (FY1)",
    "primaryMultiple": 16.76,
    "benchmarkMultiple": 20.72,
    "primaryRelative": 0.8089,
    "priceToBook": 2.74,
    "benchmarkPriceToBook": 5.41,
    "pbRelative": 0.5065,
    "crossSectionScore": 79.7,
    "trackedHistoryPercentile": null,
    "historySamples": 10,
    "valueScore": 79.7,
    "note": "Sponsor fundamentals are as of 2026-10-05. Value score blends the ETF's primary valuation multiple and P/B versus SPY. Tracked-history percentile activates after 20 samples; currently 10."
  },
  {
    "ticker": "XLE",
    "status": "automated",
    "assetClass": "equity",
    "provider": "State Street",
    "sourceUrl": "https://www.ssga.com/us/en/intermediary/etfs/state-street-energy-select-sector-spdr-etf-xle",
    "proxyTicker": null,
    "asOf": "2026-10-05",
    "primaryMetric": "Forward P/E (FY1)",
    "primaryMultiple": 12.2,
    "benchmarkMultiple": 20.72,
    "primaryRelative": 0.5888,
    "priceToBook": 2.57,
    "benchmarkPriceToBook": 5.41,
    "pbRelative": 0.475,
    "crossSectionScore": 94.2,
    "trackedHistoryPercentile": null,
    "historySamples": 10,
    "valueScore": 94.2,
    "note": "Sponsor fundamentals are as of 2026-10-05. Value score blends the ETF's primary valuation multiple and P/B versus SPY. Tracked-history percentile activates after 20 samples; currently 10."
  },
  {
    "ticker": "XLF",
    "status": "automated",
    "assetClass": "equity",
    "provider": "State Street",
    "sourceUrl": "https://www.ssga.com/us/en/intermediary/etfs/state-street-financial-select-sector-spdr-etf-xlf",
    "proxyTicker": null,
    "asOf": "2026-10-05",
    "primaryMetric": "Forward P/E (FY1)",
    "primaryMultiple": 15.12,
    "benchmarkMultiple": 20.72,
    "primaryRelative": 0.7297,
    "priceToBook": 2.29,
    "benchmarkPriceToBook": 5.41,
    "pbRelative": 0.4233,
    "crossSectionScore": 85.1,
    "trackedHistoryPercentile": null,
    "historySamples": 10,
    "valueScore": 85.1,
    "note": "Sponsor fundamentals are as of 2026-10-05. Value score blends the ETF's primary valuation multiple and P/B versus SPY. Tracked-history percentile activates after 20 samples; currently 10."
  },
  {
    "ticker": "XLI",
    "status": "automated",
    "assetClass": "equity",
    "provider": "State Street",
    "sourceUrl": "https://www.ssga.com/us/en/intermediary/etfs/state-street-industrial-select-sector-spdr-etf-xli",
    "proxyTicker": null,
    "asOf": "2026-10-05",
    "primaryMetric": "Forward P/E (FY1)",
    "primaryMultiple": 24.86,
    "benchmarkMultiple": 20.72,
    "primaryRelative": 1.1998,
    "priceToBook": 6.7,
    "benchmarkPriceToBook": 5.41,
    "pbRelative": 1.2384,
    "crossSectionScore": 28.7,
    "trackedHistoryPercentile": null,
    "historySamples": 10,
    "valueScore": 28.7,
    "note": "Sponsor fundamentals are as of 2026-10-05. Value score blends the ETF's primary valuation multiple and P/B versus SPY. Tracked-history percentile activates after 20 samples; currently 10."
  },
  {
    "ticker": "XLK",
    "status": "automated",
    "assetClass": "equity",
    "provider": "State Street",
    "sourceUrl": "https://www.ssga.com/us/en/intermediary/etfs/state-street-technology-select-sector-spdr-etf-xlk",
    "proxyTicker": null,
    "asOf": "2026-10-05",
    "primaryMetric": "Forward P/E (FY1)",
    "primaryMultiple": 25.18,
    "benchmarkMultiple": 20.72,
    "primaryRelative": 1.2153,
    "priceToBook": 12.72,
    "benchmarkPriceToBook": 5.41,
    "pbRelative": 2.3512,
    "crossSectionScore": 18.5,
    "trackedHistoryPercentile": null,
    "historySamples": 10,
    "valueScore": 18.5,
    "note": "Sponsor fundamentals are as of 2026-10-05. Value score blends the ETF's primary valuation multiple and P/B versus SPY. Tracked-history percentile activates after 20 samples; currently 10."
  },
  {
    "ticker": "XLU",
    "status": "automated",
    "assetClass": "equity",
    "provider": "State Street",
    "sourceUrl": "https://www.ssga.com/us/en/intermediary/etfs/state-street-utilities-select-sector-spdr-etf-xlu",
    "proxyTicker": null,
    "asOf": "2026-10-05",
    "primaryMetric": "Forward P/E (FY1)",
    "primaryMultiple": 16.68,
    "benchmarkMultiple": 20.72,
    "primaryRelative": 0.805,
    "priceToBook": 2.03,
    "benchmarkPriceToBook": 5.41,
    "pbRelative": 0.3752,
    "crossSectionScore": 80.2,
    "trackedHistoryPercentile": null,
    "historySamples": 10,
    "valueScore": 80.2,
    "note": "Sponsor fundamentals are as of 2026-10-05. Value score blends the ETF's primary valuation multiple and P/B versus SPY. Tracked-history percentile activates after 20 samples; currently 10."
  },
  {
    "ticker": "XLV",
    "status": "automated",
    "assetClass": "equity",
    "provider": "State Street",
    "sourceUrl": "https://www.ssga.com/us/en/intermediary/etfs/state-street-health-care-select-sector-spdr-etf-xlv",
    "proxyTicker": null,
    "asOf": "2026-10-05",
    "primaryMetric": "Forward P/E (FY1)",
    "primaryMultiple": 19.99,
    "benchmarkMultiple": 20.72,
    "primaryRelative": 0.9648,
    "priceToBook": 4.71,
    "benchmarkPriceToBook": 5.41,
    "pbRelative": 0.8706,
    "crossSectionScore": 56.8,
    "trackedHistoryPercentile": null,
    "historySamples": 10,
    "valueScore": 56.8,
    "note": "Sponsor fundamentals are as of 2026-10-05. Value score blends the ETF's primary valuation multiple and P/B versus SPY. Tracked-history percentile activates after 20 samples; currently 10."
  }
];
