export type ValuationStatus = 'automated' | 'stale' | 'not_applicable' | 'error';

export type GeneratedValuationRow = {
  ticker: string;
  status: ValuationStatus;
  assetClass: 'equity' | 'real_estate' | 'non_earnings';
  provider: string | null;
  sourceUrl: string | null;
  proxyTicker?: string | null;
  asOf: string;
  primaryMetric: string | null;
  primaryMultiple: number | null;
  benchmarkMultiple: number | null;
  primaryRelative: number | null;
  priceToBook: number | null;
  benchmarkPriceToBook: number | null;
  pbRelative: number | null;
  crossSectionScore: number | null;
  trackedHistoryPercentile: number | null;
  historySamples: number;
  valueScore: number | null;
  note: string;
};

export const valuationDataMeta = {
  "generatedAt": "2026-10-03T02:21:17Z",
  "benchmark": "SPY",
  "minimumHistorySamples": 20,
  "automatedTickers": [
    "EEM",
    "EFA",
    "IWM",
    "IYR",
    "SMH",
    "XLB",
    "XLE",
    "XLF",
    "XLI",
    "XLK",
    "XLU",
    "XLV"
  ],
  "notApplicableTickers": [
    "GLD",
    "KMLM",
    "PDBC",
    "TLT",
    "UUP"
  ],
  "providers": [
    "State Street",
    "iShares"
  ],
  "note": "Equity/real-estate valuation is automated from official sponsor pages. SMH uses SOXX as a clearly labeled semiconductor-sector valuation proxy. Non-earnings assets are intentionally not assigned P/E-style value scores."
} as const;

export const valuationRows: GeneratedValuationRow[] = [
  {
    "ticker": "EEM",
    "status": "automated",
    "assetClass": "equity",
    "provider": "iShares",
    "sourceUrl": "https://www.ishares.com/us/products/239637/ishares-msci-emerging-markets-etf",
    "proxyTicker": null,
    "asOf": "2026-10-01",
    "primaryMetric": "P/E",
    "primaryMultiple": 19.72,
    "benchmarkMultiple": 24.62,
    "primaryRelative": 0.801,
    "priceToBook": 2.73,
    "benchmarkPriceToBook": 5.31,
    "pbRelative": 0.5141,
    "crossSectionScore": 79.9,
    "trackedHistoryPercentile": null,
    "historySamples": 8,
    "valueScore": 79.9,
    "note": "Sponsor fundamentals are as of 2026-10-01. Value score blends the ETF's primary valuation multiple and P/B versus SPY. Tracked-history percentile activates after 20 samples; currently 8."
  },
  {
    "ticker": "EFA",
    "status": "automated",
    "assetClass": "equity",
    "provider": "iShares",
    "sourceUrl": "https://www.ishares.com/us/products/239623/ishares-msci-eafe-etf",
    "proxyTicker": null,
    "asOf": "2026-10-01",
    "primaryMetric": "P/E",
    "primaryMultiple": 19.18,
    "benchmarkMultiple": 24.62,
    "primaryRelative": 0.779,
    "priceToBook": 2.38,
    "benchmarkPriceToBook": 5.31,
    "pbRelative": 0.4482,
    "crossSectionScore": 81.9,
    "trackedHistoryPercentile": null,
    "historySamples": 8,
    "valueScore": 81.9,
    "note": "Sponsor fundamentals are as of 2026-10-01. Value score blends the ETF's primary valuation multiple and P/B versus SPY. Tracked-history percentile activates after 20 samples; currently 8."
  },
  {
    "ticker": "GLD",
    "status": "not_applicable",
    "assetClass": "non_earnings",
    "provider": null,
    "sourceUrl": null,
    "proxyTicker": null,
    "asOf": "2026-10-03",
    "primaryMetric": null,
    "primaryMultiple": null,
    "benchmarkMultiple": null,
    "primaryRelative": null,
    "priceToBook": null,
    "benchmarkPriceToBook": null,
    "pbRelative": null,
    "crossSectionScore": null,
    "trackedHistoryPercentile": null,
    "historySamples": 0,
    "valueScore": null,
    "note": "Gold does not have an earnings multiple comparable with SPY."
  },
  {
    "ticker": "IWM",
    "status": "automated",
    "assetClass": "equity",
    "provider": "iShares",
    "sourceUrl": "https://www.ishares.com/us/products/239710/ishares-russell-2000-etf",
    "proxyTicker": null,
    "asOf": "2026-10-01",
    "primaryMetric": "P/E",
    "primaryMultiple": 17.77,
    "benchmarkMultiple": 24.62,
    "primaryRelative": 0.7218,
    "priceToBook": 2.06,
    "benchmarkPriceToBook": 5.31,
    "pbRelative": 0.3879,
    "crossSectionScore": 85.6,
    "trackedHistoryPercentile": null,
    "historySamples": 8,
    "valueScore": 85.6,
    "note": "Sponsor fundamentals are as of 2026-10-01. Value score blends the ETF's primary valuation multiple and P/B versus SPY. Tracked-history percentile activates after 20 samples; currently 8."
  },
  {
    "ticker": "IYR",
    "status": "automated",
    "assetClass": "real_estate",
    "provider": "iShares",
    "sourceUrl": "https://www.ishares.com/us/products/239520/ishares-us-real-estate-etf",
    "proxyTicker": null,
    "asOf": "2026-10-01",
    "primaryMetric": "P/CF",
    "primaryMultiple": 16.09,
    "benchmarkMultiple": 18.25,
    "primaryRelative": 0.8816,
    "priceToBook": 2.38,
    "benchmarkPriceToBook": 5.31,
    "pbRelative": 0.4482,
    "crossSectionScore": 75.2,
    "trackedHistoryPercentile": null,
    "historySamples": 8,
    "valueScore": 75.2,
    "note": "Sponsor fundamentals are as of 2026-10-01. Value score blends the ETF's primary valuation multiple and P/B versus SPY. Tracked-history percentile activates after 20 samples; currently 8."
  },
  {
    "ticker": "KMLM",
    "status": "not_applicable",
    "assetClass": "non_earnings",
    "provider": null,
    "sourceUrl": null,
    "proxyTicker": null,
    "asOf": "2026-10-03",
    "primaryMetric": null,
    "primaryMultiple": null,
    "benchmarkMultiple": null,
    "primaryRelative": null,
    "priceToBook": null,
    "benchmarkPriceToBook": null,
    "pbRelative": null,
    "crossSectionScore": null,
    "trackedHistoryPercentile": null,
    "historySamples": 0,
    "valueScore": null,
    "note": "Managed futures do not have an earnings multiple comparable with SPY."
  },
  {
    "ticker": "PDBC",
    "status": "not_applicable",
    "assetClass": "non_earnings",
    "provider": null,
    "sourceUrl": null,
    "proxyTicker": null,
    "asOf": "2026-10-03",
    "primaryMetric": null,
    "primaryMultiple": null,
    "benchmarkMultiple": null,
    "primaryRelative": null,
    "priceToBook": null,
    "benchmarkPriceToBook": null,
    "pbRelative": null,
    "crossSectionScore": null,
    "trackedHistoryPercentile": null,
    "historySamples": 0,
    "valueScore": null,
    "note": "Broad commodities do not have an earnings multiple comparable with SPY."
  },
  {
    "ticker": "SMH",
    "status": "automated",
    "assetClass": "equity",
    "provider": "iShares",
    "sourceUrl": "https://www.ishares.com/us/products/239705/ishares-semiconductor-etf",
    "proxyTicker": "SOXX",
    "asOf": "2026-10-01",
    "primaryMetric": "P/E",
    "primaryMultiple": 68.66,
    "benchmarkMultiple": 24.62,
    "primaryRelative": 2.7888,
    "priceToBook": 11.84,
    "benchmarkPriceToBook": 5.31,
    "pbRelative": 2.2298,
    "crossSectionScore": 0.0,
    "trackedHistoryPercentile": null,
    "historySamples": 8,
    "valueScore": 0.0,
    "note": "Valuation proxy: SOXX is used for the semiconductor complex because the SMH sponsor endpoint blocks automated CI access. Sponsor fundamentals are as of 2026-10-01. Value score blends the ETF's primary valuation multiple and P/B versus SPY. Tracked-history percentile activates after 20 samples; currently 8."
  },
  {
    "ticker": "TLT",
    "status": "not_applicable",
    "assetClass": "non_earnings",
    "provider": null,
    "sourceUrl": null,
    "proxyTicker": null,
    "asOf": "2026-10-03",
    "primaryMetric": null,
    "primaryMultiple": null,
    "benchmarkMultiple": null,
    "primaryRelative": null,
    "priceToBook": null,
    "benchmarkPriceToBook": null,
    "pbRelative": null,
    "crossSectionScore": null,
    "trackedHistoryPercentile": null,
    "historySamples": 0,
    "valueScore": null,
    "note": "Long-duration Treasuries are better valued with yield/term-premium measures than P/E."
  },
  {
    "ticker": "UUP",
    "status": "not_applicable",
    "assetClass": "non_earnings",
    "provider": null,
    "sourceUrl": null,
    "proxyTicker": null,
    "asOf": "2026-10-03",
    "primaryMetric": null,
    "primaryMultiple": null,
    "benchmarkMultiple": null,
    "primaryRelative": null,
    "priceToBook": null,
    "benchmarkPriceToBook": null,
    "pbRelative": null,
    "crossSectionScore": null,
    "trackedHistoryPercentile": null,
    "historySamples": 0,
    "valueScore": null,
    "note": "A currency index does not have an earnings multiple comparable with SPY."
  },
  {
    "ticker": "XLB",
    "status": "automated",
    "assetClass": "equity",
    "provider": "State Street",
    "sourceUrl": "https://www.ssga.com/us/en/intermediary/etfs/state-street-materials-select-sector-spdr-etf-xlb",
    "proxyTicker": null,
    "asOf": "2026-10-01",
    "primaryMetric": "Forward P/E (FY1)",
    "primaryMultiple": 16.8,
    "benchmarkMultiple": 20.43,
    "primaryRelative": 0.8223,
    "priceToBook": 2.57,
    "benchmarkPriceToBook": 5.31,
    "pbRelative": 0.484,
    "crossSectionScore": 79.0,
    "trackedHistoryPercentile": null,
    "historySamples": 8,
    "valueScore": 79.0,
    "note": "Sponsor fundamentals are as of 2026-10-01. Value score blends the ETF's primary valuation multiple and P/B versus SPY. Tracked-history percentile activates after 20 samples; currently 8."
  },
  {
    "ticker": "XLE",
    "status": "automated",
    "assetClass": "equity",
    "provider": "State Street",
    "sourceUrl": "https://www.ssga.com/us/en/intermediary/etfs/state-street-energy-select-sector-spdr-etf-xle",
    "proxyTicker": null,
    "asOf": "2026-10-01",
    "primaryMetric": "Forward P/E (FY1)",
    "primaryMultiple": 12.2,
    "benchmarkMultiple": 20.43,
    "primaryRelative": 0.5972,
    "priceToBook": 2.54,
    "benchmarkPriceToBook": 5.31,
    "pbRelative": 0.4783,
    "crossSectionScore": 93.7,
    "trackedHistoryPercentile": null,
    "historySamples": 8,
    "valueScore": 93.7,
    "note": "Sponsor fundamentals are as of 2026-10-01. Value score blends the ETF's primary valuation multiple and P/B versus SPY. Tracked-history percentile activates after 20 samples; currently 8."
  },
  {
    "ticker": "XLF",
    "status": "automated",
    "assetClass": "equity",
    "provider": "State Street",
    "sourceUrl": "https://www.ssga.com/us/en/intermediary/etfs/state-street-financial-select-sector-spdr-etf-xlf",
    "proxyTicker": null,
    "asOf": "2026-10-01",
    "primaryMetric": "Forward P/E (FY1)",
    "primaryMultiple": 15.0,
    "benchmarkMultiple": 20.43,
    "primaryRelative": 0.7342,
    "priceToBook": 2.27,
    "benchmarkPriceToBook": 5.31,
    "pbRelative": 0.4275,
    "crossSectionScore": 84.8,
    "trackedHistoryPercentile": null,
    "historySamples": 8,
    "valueScore": 84.8,
    "note": "Sponsor fundamentals are as of 2026-10-01. Value score blends the ETF's primary valuation multiple and P/B versus SPY. Tracked-history percentile activates after 20 samples; currently 8."
  },
  {
    "ticker": "XLI",
    "status": "automated",
    "assetClass": "equity",
    "provider": "State Street",
    "sourceUrl": "https://www.ssga.com/us/en/intermediary/etfs/state-street-industrial-select-sector-spdr-etf-xli",
    "proxyTicker": null,
    "asOf": "2026-10-01",
    "primaryMetric": "Forward P/E (FY1)",
    "primaryMultiple": 24.61,
    "benchmarkMultiple": 20.43,
    "primaryRelative": 1.2046,
    "priceToBook": 6.64,
    "benchmarkPriceToBook": 5.31,
    "pbRelative": 1.2505,
    "crossSectionScore": 27.9,
    "trackedHistoryPercentile": null,
    "historySamples": 8,
    "valueScore": 27.9,
    "note": "Sponsor fundamentals are as of 2026-10-01. Value score blends the ETF's primary valuation multiple and P/B versus SPY. Tracked-history percentile activates after 20 samples; currently 8."
  },
  {
    "ticker": "XLK",
    "status": "automated",
    "assetClass": "equity",
    "provider": "State Street",
    "sourceUrl": "https://www.ssga.com/us/en/intermediary/etfs/state-street-technology-select-sector-spdr-etf-xlk",
    "proxyTicker": null,
    "asOf": "2026-10-01",
    "primaryMetric": "Forward P/E (FY1)",
    "primaryMultiple": 24.79,
    "benchmarkMultiple": 20.43,
    "primaryRelative": 1.2134,
    "priceToBook": 12.58,
    "benchmarkPriceToBook": 5.31,
    "pbRelative": 2.3691,
    "crossSectionScore": 18.6,
    "trackedHistoryPercentile": null,
    "historySamples": 8,
    "valueScore": 18.6,
    "note": "Sponsor fundamentals are as of 2026-10-01. Value score blends the ETF's primary valuation multiple and P/B versus SPY. Tracked-history percentile activates after 20 samples; currently 8."
  },
  {
    "ticker": "XLU",
    "status": "automated",
    "assetClass": "equity",
    "provider": "State Street",
    "sourceUrl": "https://www.ssga.com/us/en/intermediary/etfs/state-street-utilities-select-sector-spdr-etf-xlu",
    "proxyTicker": null,
    "asOf": "2026-10-01",
    "primaryMetric": "Forward P/E (FY1)",
    "primaryMultiple": 16.57,
    "benchmarkMultiple": 20.43,
    "primaryRelative": 0.8111,
    "priceToBook": 2.02,
    "benchmarkPriceToBook": 5.31,
    "pbRelative": 0.3804,
    "crossSectionScore": 79.8,
    "trackedHistoryPercentile": null,
    "historySamples": 8,
    "valueScore": 79.8,
    "note": "Sponsor fundamentals are as of 2026-10-01. Value score blends the ETF's primary valuation multiple and P/B versus SPY. Tracked-history percentile activates after 20 samples; currently 8."
  },
  {
    "ticker": "XLV",
    "status": "automated",
    "assetClass": "equity",
    "provider": "State Street",
    "sourceUrl": "https://www.ssga.com/us/en/intermediary/etfs/state-street-health-care-select-sector-spdr-etf-xlv",
    "proxyTicker": null,
    "asOf": "2026-10-01",
    "primaryMetric": "Forward P/E (FY1)",
    "primaryMultiple": 19.83,
    "benchmarkMultiple": 20.43,
    "primaryRelative": 0.9706,
    "priceToBook": 4.68,
    "benchmarkPriceToBook": 5.31,
    "pbRelative": 0.8814,
    "crossSectionScore": 56.1,
    "trackedHistoryPercentile": null,
    "historySamples": 8,
    "valueScore": 56.1,
    "note": "Sponsor fundamentals are as of 2026-10-01. Value score blends the ETF's primary valuation multiple and P/B versus SPY. Tracked-history percentile activates after 20 samples; currently 8."
  }
];
